### ISSUE TITLE
🐞[BUG] Infinity spinners in claiming stacking reward tab when user haven't stack at all

### ISSUE THREAD

**Issue by LNow** [citycoins/ui#106]
**Describe the bug**
If user haven't stack at all when he visits a page where we can claim stacking reward he will se multiple infinite spinners.

**To Reproduce**
1. Create new wallet
2. Login to UI with new wallet
3. Visit stacking page
4. Click on `Claim Rewards` tab

**Expected behavior**
User should see an information that he have not stacked.

**Screenshots**
![image](https://user-images.githubusercontent.com/829210/141024341-96608e8c-9d9d-425e-bab9-93e96a0f59f4.png)

**Comment by whoabuddy** [comment]
Closing because this issue is no longer relevant after the redesign.
