### ISSUE TITLE
Rename repository `citycoin-ui` -> `ui`

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/ui#127]
This repository was one of the first created in the org, and its naming is inconsistent with the rest of the projects:

- citycoin
- **citycoin-ui**
- api
- docs
- governance
- scripts

The upgrade is a good time to rename the `citycoin-ui` repository to `ui`, and GitHub will automatically handle redirects.

**Comment by whoabuddy** [comment]
Done!

**Comment by Palenyj1981** [comment]
Good bro

вт, 19 квіт. 2022, 19:11 користувач Jason Schrader ***@***.***>
пише:
