### ISSUE TITLE
Replace substr() method with substring()

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/ui#146]
**Is your feature request related to a problem? Please describe.**

The address component uses the `substr()` method which is deprecated.

**Describe the solution you'd like**

Any usage of `substr()` should be replaced with `substring()`.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

**Comment by phershbe** [comment]
I'm trying to get experience and found this on an aggregator listing good first issue tags. I can work on this if you're accepting contributors.

**Comment by whoabuddy** [comment]
Sure, that'd be great! Basic process would be to:

- fork the repository
- create a branch for the changes
- submit a PR back with the changes

Happy to help with any questions along the way.

If you're on Discord you can join the [CityCoins server](https://discord.gg/citycoins) as well - there are a few areas for builders.

**Comment by phershbe** [comment]
@whoabuddy Awesome, thank you, I'll get it in later today!!

**Comment by phershbe** [comment]
@whoabuddy sorry about the delay, something came up yesterday. I'm working on it now. So when I search in the main branch of the unforked repository for "substr()" in the search bar, it brings up instances existing in the branch 1a620c0596. When I search for "substr()" in my fork, it doesn't find any results. Should I have forked branch 1a620c0596 instead of the main branch?

**Comment by whoabuddy** [comment]
You should checkout the `develop` branch and create the PR from there, it's the main one that has the most recent code, and once enough changes are finalized it's released to `main`.

As far as the search I think it's a simple fix: `substr()` won't match anything because the commands contain values between `(` and `)`, e.g. `{addr.substr(0, 5)}...{addr.substr(addr.length - 5)}`. If you search for just `substr` instead you'll see the components that use it:
https://github.com/citycoins/ui/search?q=substr

**Comment by randr000** [comment]
@phershbe are you still having trouble with this? If you are, I can give it a try. Thanks.

**Comment by phershbe** [comment]
@randr000 I'm still working on it, I don't like giving up on things. I'm still trying to figure out why substr won't show up in the search on my fork.

**Comment by phershbe** [comment]
@whoabuddy that's good to know about searching for `substr` and not `substr()`, that's a stupid mistake and it's good to learn from. It still finds `substr()`, I probably searched both ways before too. In any case, I'm still having problems. Here are some screenshots:

**Searching in the unforked repository:**

<img width="761" alt="searchsuccess" src="https://user-images.githubusercontent.com/25594870/172257591-b7d6237f-6053-44b2-8fbd-1cec40aee7b5.png">

**The fork that I created:**

<img width="793" alt="myfork" src="https://user-images.githubusercontent.com/25594870/172260170-3f983bfe-b33d-4d5a-bd35-025927b810f1.png">

**Searching in my forked repository:**

<img width="702" alt="searchfailure" src="https://user-images.githubusercontent.com/25594870/172257637-5da87058-bae9-4299-b972-09f552984cc8.png">

**Comment by whoabuddy** [comment]
One option is to delete the fork and start over - sometimes something funny happens between and a fresh start eliminates any weirdness.

If I couldn't find it via the search then I'd look for those components in their directories and see if the code matches what I expect to see, e.g. https://github.com/citycoins/ui/blob/develop/src/components/profile/Address.js#L11-L13

Does that component/folder structure look the same as your fork? If not, you may be on the wrong branch?

**Comment by phershbe** [comment]
@whoabuddy Thank you for your patience, I'm learning a lot here and hopefully can get this resolved quickly.

Deleting the fork and starting over didn't work.

So in the search for `substr` in my fork, the `issues` tab was selected in the search. When I changed the tab to `code`, it gave me "Sorry, forked repositories are not currently searchable.". Okay so I searched `substr` again in the unforked repository and it found five files:

[src/components/Address.js](https://github.com/citycoins/ui/blob/1a620c059684316e6c7acebf9036164bbf061876/src/components/Address.js)
[src/components/Tx.js](https://github.com/citycoins/ui/blob/1a620c059684316e6c7acebf9036164bbf061876/src/components/Tx.js)
[src/components/TxStatus.js](https://github.com/citycoins/ui/blob/1a620c059684316e6c7acebf9036164bbf061876/src/components/TxStatus.js)
[src/lib/transactions.js](https://github.com/citycoins/ui/blob/1a620c059684316e6c7acebf9036164bbf061876/src/lib/transactions.js)
[src/components/CityCoinTxList.js](https://github.com/citycoins/ui/blob/1a620c059684316e6c7acebf9036164bbf061876/src/components/CityCoinTxList.js)

Clicking on them, however, shows me files in the 10620c0596 branch. I then searched for them in the `develop` branch by clicking through the `components` and `lib` folders and couldn't find most of them (Tx.js, TxStatus.js, transactions.js, CityCoinTxList.js) anywhere except for the Address.js file that you mentioned in the previous comment. My logic there was that if I could find them by clicking through folders, I could still go in and change them in my fork.

Am I correct in my reasoning and results above?

**Comment by whoabuddy** [comment]
@phershbe No problem! I still suspect what's happening here is related to the default branch `main` vs `develop` where the most recent changes live. The paths you have listed above are linked to commit 1a620c059684316e6c7acebf9036164bbf061876, which is definitely a much older one.

![Screenshot from 2022-06-07 06-00-17](https://user-images.githubusercontent.com/9038904/172385997-a5addf2c-8559-4796-bb04-b5c69e68a14f.png)

The search also isn't working as expected for me, I ended up using the search in VS Code to find which files: it's just the LinkTx.js and Address.js components.

Depending on how you're accessing things (website, command-line, etc) there are a few steps to make sure you see the right files. Here are links to the two components on the develop branch:

https://github.com/phershbe/ui/blob/develop/src/components/profile/Address.js
https://github.com/phershbe/ui/blob/develop/src/components/common/LinkTx.js

You can also [sync your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) beforehand as it's two commits behind.

**Comment by chhetri28** [comment]
Hey @whoabuddy I've replaced the substr() method with substring() on both of the file.

I'm new to this, could you please tell what's the next step?

**Comment by phershbe** [comment]
@whoabuddy Awesome, thank you for your help and the detail in answering my questions. Yeah I kind of thought about searching in Visual Studio Code before, I didn't think it would give me different results or something, that's great advice though.

These kinds of challenges are good because I learn a lot from them, it took some time and effort from you though to help so thank you.

I'm going to browse through the issues and see what else I could help with.

**Comment by phershbe** [comment]
@chhetri28 @whoabuddy I requested to work on this and was assigned it and did a lot of work to figure it out, I should probably be the person submitting the pull request unless somebody says otherwise. Another pull request was made randomly following information that was posted on here answering my questions. I'm trying to get experience and proof of experience. It's not a big deal but I should get credit for doing the work in the form of hopefully an accepted pull request.
