### ISSUE TITLE
🐞[BUG] Can't claim rewards/stacked coins

### ISSUE THREAD

**Issue by shaneafsar** [citycoins/ui#166]
**Describe the bug**
Tapping the "Claim" button doesn't result in anything happening.

**To Reproduce**
1. Go to https://minecitycoins.com/stacking?chain=mainnet
2. Scroll down to Claim NYC Stacking Rewards
4. Click on "Claim" for a particular row that has the button

**Expected behavior**
Initiate transfer to Hiro wallet.

**Screenshots**
![Screenshot 2023-08-21 at 12 57 43 PM](https://github.com/citycoins/ui/assets/1145967/790a43b1-eb7f-463c-a65a-9c09992f44c7)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version  115.0.5790.170

**Comment by whoabuddy** [comment]
Thanks for reporting this! That line refers to the post-conditions set by the UI for the transaction, see here:

```ts
data.toReturn > 0 &&
    postConditions.push(
      makeContractFungiblePostCondition(
        citySettings.config.stacking.deployer,
        citySettings.config.stacking.stackingClaimContract,
        FungibleConditionCode.Equal,
        amountCityCoinsCV.value,
        createAssetInfo(
          citySettings.config.token.deployer,
          citySettings.config.token.contractName,
          citySettings.config.token.tokenName
        )
      )
    );
```

The citySettings.config is set a bit earlier, and should contain the contract and version depending on where you are trying to claim from.

Are there any other console errors? If you clear your cache and try again does it work? 

Also if you can share a txid or address that can help narrow it down.

**Comment by Palenyj1981** [comment]
Привіт друзі.  Яку відповідь?

пт, 2 серп. 2024 р., 20:13 користувач Shane Afsar ***@***.***>
пише:
