### ISSUE TITLE
Profile: small profile component should indicate network status

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/ui#19]
I love jdenticons, but I am worried the user will not realize what this is and be distracted by it.

It'd be easier to just use a small STX logo since it's next to a STX address anyway.

**Comment by friedger** [comment]
Then don't show anything next to the address.

Can we use the explorers' icons?

**Comment by whoabuddy** [comment]
Yes, but let's also use the icon to display network status, i.e.

![image](https://user-images.githubusercontent.com/9038904/122646893-1f889680-d0e7-11eb-8c26-c22cadcfc5fe.png)

So, final layout would be:

- match explorer icon if on mainnet (matches experience, I like that idea)
- green circle icon if on testnet
- orange circle icon if on regtest
- yellow circle icon if on mocknet

That way it's very clear and coincides with network selection in the wallet. Thinking of this in relation to https://github.com/citycoins/citycoin/issues/65 and having people change their network in the wallet for testing.

**Comment by whoabuddy** [comment]
![image](https://user-images.githubusercontent.com/9038904/122791733-576e1600-d26e-11eb-9dd4-173d0e7c08ea.png)

This small profile component could display network status by coloring the icon, similar to the thought above, and when clicked the large profile component can display the jdenticon (or explorer icon). At that point, I do not think the icon is as confusing to the user :)

**Comment by phouchens** [comment]
I am interested in tackling this issue. A couple of questions, how do I simulate changing the networks locally?  Is the network type held in state somewhere or do we get that from a service (@stacks/network maybe?).

**Comment by whoabuddy** [comment]
@phouchens that's great! I had an idea for this that should be pretty straight-forward. Bootstrap has a [feature for badges](https://getbootstrap.com/docs/5.0/components/badge/), and a small circle absolutely positioned top-right on the small profile icon would be perfect: orange for testnet, green for mainnet.

The network type is stored in `src/lib/stacks.js` here based on the URL:
https://github.com/citycoins/citycoin-ui/blob/a032845cf5778297539d076f910e0174a805f239/src/lib/stacks.js#L3

An example of how it's used can be seen in the `src/components/common/LinkTx.js` file:
https://github.com/citycoins/citycoin-ui/blob/a032845cf5778297539d076f910e0174a805f239/src/components/common/LinkTx.js#L1-L11

**Comment by phouchens** [comment]
Thanks for the feedback, i have a PR for this, but don't seem to have the permissions to push.

**Comment by whoabuddy** [comment]
Generally you'd fork the repo first, create a branch, then send a PR back with that - if you run into an issue though happy to work it out.

**Comment by whoabuddy** [comment]
Fixed in #114
